### ISSUE TITLE
switching a buffer while sticky header is visible

### ISSUE THREAD

**Issue by andreyorst** [jclasley/sticky-scroll-mode#3]
Hello.

After switching a buffer the sticky header remains visible:

![image](https://github.com/user-attachments/assets/9dec3b57-7daf-4bce-bd2e-1e85a69c0484)

I understand that this is a buffer with no decoration, but this behavior is a bit unexpected.

Maybe a childframe, that updates its its width and position based on original buffer window would be a better solution?

**Comment by jclasley** [comment]
Thank you for the issue!

This is interesting. Navigating away from the buffer's window should kill the window and buffer.

If you don't mind, what command(s) did you do to produce this bug?

**Comment by andreyorst** [comment]
> If you don't mind, what command(s) did you do to produce this bug?

Just C-x b and chose another buffer


-- 
Andrey Listopadov

**Comment by andreyorst** [comment]
maybe it's because I'm using vertico

**Comment by jclasley** [comment]
See the issue now! Will be resolved shortly
